### ISSUE TITLE
plugin not found after add 

### ISSUE THREAD

**Issue by elevensky** [ntnyq/omz-plugin-pnpm#4]
`
Last login: Fri Jan 14 10:37:18 on ttys000
[oh-my-zsh] plugin 'pnpm' not found
`
my config
![image](https://user-images.githubusercontent.com/6904834/149443885-7ab1e770-819f-42b5-ba89-9cad2c34d4c9.png)
![image](https://user-images.githubusercontent.com/6904834/149443966-5f4f5d34-2acf-45b9-993c-90a04a19b797.png)

restart my item2, but still not fount @ntnyq

**Comment by ntnyq** [comment]
rename folder `omz-plugin-pnpm` to `pnpm` and run `source  ~/.zshrc`

**Comment by elevensky** [comment]
![image](https://user-images.githubusercontent.com/6904834/152711488-420de4f9-6a2e-4b68-b6ff-81298b25413d.png)

**Comment by elevensky** [comment]
it's right way, thks @sarasate
