### ISSUE TITLE
pnpm plugin: pnpm not found.

### ISSUE THREAD

**Issue by vndre** [ntnyq/omz-plugin-pnpm#5]
I'm not good with zsh syntax but if I get it right `$+commands[pnpm]` evaluates to `1` and thus `!1` should skip the if statement?

![Screenshot 2022-01-28 170838](https://user-images.githubusercontent.com/13294924/151634205-3e7a2ffb-7a8b-400d-b737-950125551912.png)

**Comment by trathailoi** [comment]
the same to me

**Comment by ntnyq** [comment]
The pnpm command check has been removed.

**Comment by vndre** [comment]
this issue was fixed in latest commit, thank you @ntnyq
