### ISSUE TITLE
ps is the default command on Unix/Linux systems and should not be alias

### ISSUE THREAD

**Issue by persiliao** [ntnyq/omz-plugin-pnpm#6]
https://github.com/ntnyq/omz-plugin-pnpm/blob/d2cadcc70baa682e74f60770dbabfde6cfdacf11/pnpm.plugin.zsh#L30

**Comment by ntnyq** [comment]
Thanks for your report.

It has been renamed to `psv` in the latest commit.

See [CHANGELOG](https://github.com/ntnyq/omz-plugin-pnpm#changelog) here for the whole change.
